application:
  bindAddress: :8446
  production: false
  debug: false
database:
  address: localhost:3402
  name: collector
  username: tradalia
  password: tradalia
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
  clientId: algotiqa-backend
  clientSecret: ddKGvsqWMKQT4v4lWS03Jr9i3ZEJHzv1
platform:
  system: https://algotiqa-server:8449/api/system
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
datastore:
  address: localhost:3410
  name: datastore
  username: tradalia
  password: tradalia
  staging:  staging
